---
name: BetterMinion
main: Mcbeany\BetterMinion\BetterMinion
version: 1.0.0
api: 4.0.0
authors:
- Mcbeany
- AIPTU
src-namespace-prefix: Mcbeany\BetterMinion

permissions:
  betterminion.command:
    default: op
    description: Allows users to use better minion command
...
